### ISSUE TITLE
Name Preprocessor propose

### ISSUE THREAD

**Issue by DukeCheng** [efcore/EFCore.NamingConventions#157] opened 2022-09-15 11:17 UTC
I usually like to add a suffix for Persist Object class naming, 
example for `UserEntity,` and expected table name `User`,  Class Name: `UserEntity` => TableName: `User`

So is there have a name preprocessor for this let me to remove the suffix when convert the name, 
If doesn't have yet,  I can commit a pr to support the NamePreprocessor, do you have any suggest?

**Comment by roji** [comment] 2022-09-15 11:22
@DukeCheng what's the rule here? When is which suffix supposed to be removed?

**Comment by roji** [comment] 2022-09-15 11:33
@DukeCheng that sounds like a dup of #42

**Comment by roji** [comment] 2022-09-15 11:45
Duplicate of #42

**Comment by roji** [comment] 2022-09-15 11:46
Nobody's working on that for now. I'm heads-down working on EF Core 7.0 and related urgent things, typically shortly before or after the release I do a work cycle on this plugin (at the very least to make it compatible with the new EF Core release). I might be able to do that as part of that.

**Closed by roji** 2022-09-15 11:46 UTC
