### ISSUE TITLE
Only column names are affected, table names remain in default case

### ISSUE THREAD

**Issue by pm64** [efcore/EFCore.NamingConventions#6] opened 2020-01-07 11:50 UTC
I'm using this package for a project that uses ASP.Net Identity. It appears to be working, however only my column names wind up in snake_case -- table names AreStillTheSame.

This accepted answer to a recent SO post (https://stackoverflow.com/questions/59286100/aspnetcore-identity-using-postgresql-how-to-create-structure) shows that the author had to bring additional logic into OnModelCreating() to handle the table names, iterating over each entity and converting individually.

The EFCore.NamingConventions docs suggest that using UseSnakeCaseNamingConvention() in OnConfiguring() alone will handle both table and column names ("This will automatically make all your table and column names have snake_case naming").

I sincerely doubt the EFCore.NamingConventions docs are wrong and the random SO dude is right, even if his approach works. What am I missing?

**Comment by roji** [comment] 2020-01-16 19:19
Duplicate of #2

**Closed by roji** 2020-01-16 19:19 UTC
