### ISSUE TITLE
Asp.Net Identity does not work due to snake casing not applied by the library

### ISSUE THREAD

**Issue by md-owes** [efcore/EFCore.NamingConventions#300] opened 2024-12-10 15:14 UTC
Hi, 

I followed through the readme and added below code in my identity access microservice which uses Asp.Net Identity Core to authenticate user.
     
```
     public class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : IdentityDbContext<ApplicationUser>(options)
      {
          protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
          {
              optionsBuilder.UseSnakeCaseNamingConvention();
          }
      }
```

My database is setup to use postgresql which has all table and column names in snake case. My expectation was that the above code will automatically instruct EF Core to use snake casing for table names (for e.g. asp_net_users table will be queries instead of AspNetUsers table), but it throws a runtime exception as soon the first request to my endpoint (which is hosted as a separate microservice in a container) is made by the browser to authenticate user.

The exception message is as follows 

> Npgsql.PostgresException (0x80004005): 42P01: relation "AspNetUsers" does not exist

I am using version 9 of EfCore.NamingConventions and my EF Core and entire application is setup to use .Net 9.

**Comment by md-owes** [comment] 2024-12-10 15:16
Note: I do not use migrations from ef core but rather use my own scripts to create all the tables (including asp.net identity tables) and also seed all tables with initial data in my database/

**Comment by roji** [comment] 2024-12-11 10:50
Duplicate of #2

**Closed by roji** 2024-12-11 10:50 UTC
