### ISSUE TITLE
Regression in 7.0.2: TPH table names are not being rewritten

### ISSUE THREAD

**Issue by Kukkimonsuta** [efcore/EFCore.NamingConventions#184] opened 2023-01-16 12:56 UTC
When using TPH, table name is not being rewritten - following example creates tables `blogs` (correct) and `Posts` (incorrect). This behavior was correct in version 7.0.0

Repro:
```cs
using Microsoft.EntityFrameworkCore;

class Blog
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; }
}

abstract class Post
{
    public int Id { get; set; }
    public Blog Blog { get; set; }
    public int Blog_Id { get; set; }
}
class InternalPost : Post { }
class ExternalPost : Post { }

class TestContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; } = null!;
    public DbSet<Post> Posts { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseNpgsql("Server=localhost;Database=testefnamingconventions_local;User Id=postgres;Password=root;");
        optionsBuilder.UseLowerCaseNamingConvention();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Blog>().HasMany(x => x.Posts).WithOne(x => x.Blog).HasForeignKey(x => x.Blog_Id);
        modelBuilder.Entity<Post>().HasOne(x => x.Blog).WithMany(x => x.Posts).HasForeignKey(x => x.Blog_Id);
        modelBuilder.Entity<InternalPost>();
        modelBuilder.Entity<ExternalPost>();
    }
}
```

Generated migration:
```cs
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace testefnamingconventions.Migrations
{
    /// <inheritdoc />
    public partial class InitialStructure : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "blogs",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_blogs", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Posts",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    blogid = table.Column<int>(name: "blog_id", type: "integer", nullable: false),
                    discriminator = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_posts", x => x.id);
                    table.ForeignKey(
                        name: "fk_posts_blogs_blogid",
                        column: x => x.blogid,
                        principalTable: "blogs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_posts_blog_id",
                table: "Posts",
                column: "blog_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Posts");

            migrationBuilder.DropTable(
                name: "blogs");
        }
    }
}
```

btw: Thank you for quickly solving #179 ❤️

**Comment by dean-dot-git** [comment] 2023-01-18 04:45
I second this.  It is breaking several of our data pulls when we move to that version.

**Comment by Kukkimonsuta** [comment] 2023-01-18 09:59
If you need to update to 7.0.2 there is simple workaround - manually map affected entities to their tables (see below) as everything else seem to be rewritten properly. It is enough to set the name on your TPH root entities.

```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // https://github.com/efcore/EFCore.NamingConventions/issues/184
    modelBuilder.Entity<User>().ToTable("users");
    modelBuilder.Entity<Grant>().ToTable("grants");
    modelBuilder.Entity<Setting>().ToTable("settings");
}
```

**Comment by roji** [comment] 2023-01-18 10:36
Sorry about this, I'll take a look as soon as I can.

**Comment by 0Lucifer0** [comment] 2023-03-24 01:43
@roji unsure but wouldn't this be the issue ? If i understand correctly we prevent naming of abstract class to apply. https://github.com/efcore/EFCore.NamingConventions/commit/8ce1fb1bb043bc8d6b360ef11da9efbf74c1ee72#diff-340b0b728e82bffdba8e561a04c249bbe989fd2e0ccfe93ac0906191a70af34aL63

I believe the code you want is only in case of TPC
if (entityType.GetTableName() is { } tableName && ( entityType.GetMappingStrategy() != RelationalAnnotationNames.TpcMappingStrategy || !entityType.ClrType.IsAbstract))

**Comment by at-besa** [comment] 2023-05-13 18:12
> @roji not too sure as I did not test it but wouldn't this be the issue ? If i understand correctly we prevent naming of abstract class to apply. [8ce1fb1#diff-340b0b728e82bffdba8e561a04c249bbe989fd2e0ccfe93ac0906191a70af34aL63](https://github.com/efcore/EFCore.NamingConventions/commit/8ce1fb1bb043bc8d6b360ef11da9efbf74c1ee72#diff-340b0b728e82bffdba8e561a04c249bbe989fd2e0ccfe93ac0906191a70af34aL63)
> 
> I believe you want to prevent abstract class only in case of TPC `if (entityType.GetTableName() is { } tableName && (entityType.GetMappingStrategy() != RelationalAnnotationNames.TpcMappingStrategy || !entityType.ClrType.IsAbstract))`

sadly i think the problem comes with the line 37 of EFCore.NamingConventions/Internal/NameRewritingConvention.cs where it says 
`if (entityType.BaseType is null && !entityType.ClrType.IsAbstract)`
i tried to fetch the mapping strategy there but at the time of the entityType being abstract the mapping strategy is null.

what clearly is missing is a test where an abstract class with the mapping strategy TPH is done, because this shows the problem.
i have forked this and added such a test which clearly fails. 
https://github.com/at-besa/EFCore.NamingConventions/commit/0be190c6c8990ddeb4c736f07c1a2af91c601e1a

sadly i was yet not able to fix that problem.

**Comment by at-besa** [comment] 2023-05-31 11:25
thanks for that solution @erwan-joly! hopefully @roji accepts the PR

**Comment by at-besa** [comment] 2023-09-22 07:19
@roji are you gonna allow that PR before .net 8? 
7.0.2 was released in january and this still affects several projects.

**Comment by roji** [comment] 2023-09-22 07:30
@at-besa I unfortnuately simply haven't had any time in recent months to work on this plugin... In a few weeks I should be able to set aside a day or two for 8.0 preparation, I'll try to also do the pending 7.0 work as well (like this PR).

**Comment by aradalvand** [comment] 2023-11-14 23:07
Any updates on this Shay? Now that EF8 has been released?

**Comment by roji** [comment] 2023-11-14 23:31
@aradalvand I'll try to find some time for this plugin, but right at the moment there's simply too much going on.

**Comment by xamir82** [comment] 2023-11-14 23:35
@roji Since @bricelam has already upgraded the library to EF8 and .NET 8, all that's left may be just a matter of merging #199 and releasing v8.0.0.

**Comment by roji** [comment] 2023-11-15 00:32
I understand the impatience, but I can't just merge a PR without fully understanding what it does and whether it fixes the problem correctly (without introducing a bug etc.).

If you just want to use 8.0.0 regardless of this specific bug, you can use rc.2 for now.

**Comment by erwan-joly** [comment] 2023-11-15 02:55
> I understand the impatience, but I can't just merge a PR without fully understanding what it does and whether it fixes the problem correctly (without introducing a bug etc.). And that takes time.
> 
> If you just want to use 8.0.0 regardless of this specific bug, you can use rc.2 for now.

I think the reason for people to want this is because it will most likely block them from upgrading to 8.0.0 if they use TPH as this most likely made them never upgrade to 7.0.2.

That being said it’s quite important for people to understand this is an opensource project. People (in this case @roji ) are most likely spending their free time on this so it’s quite important to respect the fact they may just not have time right now to update it.

A solution remains if you want to upgrade to 8.0.0 with TPH : publish a fork on nuget until the fix get merged or reworked.

**Comment by roji** [comment] 2023-11-15 10:08
Thanks @erwan-joly, I do agree that this is a blocking regression; I may not have time to do considerable work on this plugin, but I do intend to at least fix this before releasing the official 8.0.0.

Once I finish with more things urgent (like releasing Npgsql and EFCore.PG 8.0.0), I'll take a look here.

**Comment by xamir82** [comment] 2023-11-21 16:53
@roji Don't mean to be pushy at all but just wanted to ask now that EFCore.PG 8.0 has been released (great work!), could you take a look at this now? Thank you <3

**Comment by roji** [comment] 2023-11-21 17:08
@xamir82 EFCore.PG was released yesterday night - I do intend to fix this regression in the coming weeks and then publish EFCore.NamingConventions 8.0, but you'll have to be a bit more patient.

**Comment by UliPlabst** [comment] 2023-11-21 17:15
@xamir82 did you see the really easy workaround above by @Kukkimonsuta ? This issue should not block you from moving to .net8.

**Comment by xamir82** [comment] 2023-11-21 20:04
@UliPlabst Thank you for pointing that out, I didn't see it before actually. Good to know.

**Closed** 2023-12-23 21:40 UTC
Labels: bug
