### ISSUE TITLE
add protect Naming Convention

### ISSUE THREAD

**Issue by Varorbc** [efcore/EFCore.NamingConventions#224] opened 2023-10-23 07:03 UTC
For example, I have column `A`, and I want this column to map to column `XXX`

**Comment by roji** [comment] 2023-10-23 09:23
@Varorbc that's very vague. What would be the logic of the convention, when exactly would it transform what name to what?

**Comment by roji** [comment] 2023-10-23 09:45
What's the use-case for obfuscating your own table and column names?

**Comment by roji** [comment] 2023-10-23 10:18
I'm just asking why you'd want to do this.

**Comment by roji** [comment] 2023-10-23 10:35
This is usually called "obfuscation". This seems quite odd to me; the important thing to do would be to encrypt the actual data, not to rename tables and column names... Obfuscation also doesn't actually protect anything, it just makes it a bit harder to reverse-engineer the meaning of your names.

I've never heard of anyone doing this in a database.

In any case, this plugin can't possibly support each and every idea someone has for a naming convention... I think this falls under a general feature where users would be able to provide their own naming convention as a function (#42). This would also allow you to choose your own obfuscation algorithm rather than the plugin choosing one for you.

So I'll go ahead and close this as a duplicate of #42.

**Comment by roji** [comment] 2023-10-23 10:35
Duplicate of #42.

**Closed by roji** 2023-10-23 10:35 UTC
