### ISSUE TITLE
Not making any changes to table names, but does columns

### ISSUE THREAD

**Issue by 10GeekJames** [efcore/EFCore.NamingConventions#21] opened 2020-04-11 21:20 UTC

**Comment by 10GeekJames** [comment] 2020-04-11 21:27
![image](https://user-images.githubusercontent.com/5634551/79055267-b3282280-7c19-11ea-8c1f-b75dae94701d.png)

**Comment by roji** [comment] 2020-04-12 17:51
Duplicate of #2

**Comment by roji** [comment] 2020-04-12 17:52
This is a problem specific to ASP.NET Identity. Note that you can use the workaround detailed here: https://github.com/efcore/EFCore.NamingConventions/issues/2#issuecomment-612651161

**Closed by roji** 2020-04-12 17:52 UTC
