### ISSUE TITLE
Another naming convention ( ALL_CAPS )

### ISSUE THREAD

**Issue by Narine-P** [efcore/EFCore.NamingConventions#99] opened 2021-11-03 11:06 UTC
Hi, 
I have to work with database, where all tables(TABLE_NAME) and columns are like FULL_NAME.
So, is it possible to add naming convention for FullName=>FULL_NAME ? 

I'm using EF CORE 3.1

**Comment by roji** [comment] 2021-11-10 10:03
Duplicate of #31

**Comment by roji** [comment] 2021-11-10 10:03
This is already implemented simply do UseUpperSnakeCaseNamingConvention. I'll update the README to make it documented.

**Closed by roji** 2021-11-10 10:03 UTC

**Comment by Narine-P** [comment] 2021-12-02 15:50
Thank you!
