### ISSUE TITLE
Provides a custom extension to support name conversion of a specified string

### ISSUE THREAD

**Issue by saber-wang** [efcore/EFCore.NamingConventions#138] opened 2022-05-07 10:21 UTC
For example, we can provide extension methods such as' hascolumnnameconventions' and 'totableconventions'. When these methods are used, name conversion is also supported
```
builder.Entity<test>(u=>{
u.ToTableConventions("table1");
u.Property(c => c.ColumnName).HasColumnNameConventions("ColumnName1");
});
```

**Comment by roji** [comment] 2022-05-07 18:47
It's not clear exactly what the proposed methods do - do they simply set the table and column names on the entity and property on which they're specified? If so, that's already supported in EF Core without this plugin, [see the docs](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-names).

**Comment by saber-wang** [comment] 2022-05-08 06:05
@roji  Yes, I know this API, but I want to support case conversion on this basis.

**Comment by roji** [comment] 2022-05-08 10:44
@saber-wang your proposed code above calls ToTableConventions for a single entity type (`test`), so it seems like it would affect only that entity type? How is that a convention - which presumably would affect multiple entity types/tables rather than just one? The same applies to the proposed HasColumnNameConventions - it's only defined on a single property.

You'll need to clarify what exactly you're looking for here.

**Comment by saber-wang** [comment] 2022-05-08 13:00
@roji The current convention is to convert only the attributes that do not call 'hascolumnname'. I hope to provide a conversion way for the attributes specified by 'hascolumnname' and other methods in this way, and work with the current converter to provide a consistent experience It mainly solves the problem of linking multiple databases (the current conversion mode is determined according to the configuration provided)

**Comment by roji** [comment] 2022-05-08 19:31
Are you saying that you'd like a convention which applies *after* the user's explicit HasColumnName has been called, and which performs some transformation on that user-provided name? This is still not clear to me - in the above code, there is no call to HasColumnName: please provide a full code sample illustrating exactly what you're looking for.

Note that if the above is what you're looking for, then it's not possible - by design, a convention can never override what the user explicitly sets.

**Comment by saber-wang** [comment] 2022-05-09 00:57
@roji  I agree with this Convention, but can provide additional ways to extend it.

Examples
```
public const string AnnotationColumnName = "Relational:ColumnName_Conventions";
   public static PropertyBuilder<TProperty> HasColumnNameConventions<TProperty>(this PropertyBuilder<TProperty> propertyBuilder, string name)
        {
((PropertyBuilder)propertyBuilder).Metadata.SetOrRemoveAnnotation(AnnotationNameContant.AnnotationColumnName, name);
            return propertyBuilder;
        }
```

```
public void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
        {
     //code
                 var columnAnnotation = property.FindAnnotation(AnnotationNameContant.AnnotationColumnName);
                    if (columnAnnotation != null)
                        property.SetColumnName(_namingNameRewriter.RewriteName(columnAnnotation?.Value?.ToString()));
    //code
        }
```

**Comment by roji** [comment] 2024-01-03 16:46
Sorry for dropping out of this conversation.

To the best of my understanding, you're asking for a Fluent API that would allow you to flag which properties should get their names rewritten; in other words, the name rewriting convention would only apply to properties where the proposed Fluent API has been called.

If that's indeed the case, then that seems like quite a convoluted way to go about it... If what you want is to call an explicit Fluent API on a property-by-property basis, than that Fluent API may as well just perform the name rewriting in-place, without any need for any convention. And that doesn't require anything from this plugin.

I'm going to go ahead and close this as the issue has been open for a while without additional user interest, and as things stand I don't really see the sense of it. But if I've misunderstood or you have information to add, please fee free to post back here.

**Closed by roji** 2024-01-03 16:46 UTC
