### ISSUE TITLE
Query configured convention inside OnModelCreating()

### ISSUE THREAD

**Issue by springy76** [efcore/EFCore.NamingConventions#143] opened 2022-06-23 16:40 UTC
I can capture `DbContextOptions` from ctor in private field but I don't get any usable info out of it (nor the `DbContext` itself), for example the registered `INameRewriter`.

Usage would be manual `ToTable()` calls for many-many relationships (backed by Dictionary<string,object> shared type).

Since there are multiple providers which produce options (not just postgre) I want to follow the same rules defined there.

**Comment by roji** [comment] 2022-06-23 18:37
Can you provide more context on exactly what you're trying to do and why?

**Comment by springy76** [comment] 2022-06-24 07:09
Taking this official example: https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#joining-relationships-configuration

```c#
INameRewriter rewriter = TryRetrieveConfiguredRewriterSomeHow() ?? new NoNameRewriter(); // pseudo-code

modelBuilder.Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity<Dictionary<string, object>>(
        rewriter("PostTag"),
        j => j
            .HasOne<Tag>()
            .WithMany()
            .HasForeignKey(rewriter("TagId"))
            .HasConstraintName(rewriter("FK_PostTag_Tags_TagId"))
            .OnDelete(DeleteBehavior.Cascade),
        j => j
            .HasOne<Post>()
            .WithMany()
            .HasForeignKey(rewriter("PostId"))
            .HasConstraintName(rewriter("FK_PostTag_Posts_PostId"))
            .OnDelete(DeleteBehavior.ClientCascade));
```

**Comment by roji** [comment] 2024-01-03 16:39
Sorry for not responding to this.

> I can capture DbContextOptions from ctor in private field but I don't get any usable info out of it (nor the DbContext itself), for example the registered INameRewriter.

DbContextOptions exposes the Extensions property, which is where the plugin registers its NamingConventionsOptionsExtension. However, that only has the configured NamingConvention enum, which tells NamingConventionSetPlugin which rewriter to instantiate and pass to the conventions it registers. In other words, the plugin definitely isn't set up to expose the configured rewriter. If you need to know which rewriter is registered,I suggest you keep track of that yourself outside the plugin, i.e. when actually registering the plugin.

I'm going to go ahead and close this as the issue is old, but if you have further questions feel free to post back here.

**Closed by roji** 2024-01-03 16:39 UTC
