### ISSUE TITLE
"Method not found" via MissingMethodException

### ISSUE THREAD

**Issue by dean-dot-git** [efcore/EFCore.NamingConventions#162] opened 2022-09-29 22:23 UTC
Getting the following error creating the db context using:

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSnakeCaseNamingConvention();
        base.OnConfiguring(optionsBuilder);
    }

ERROR

System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IEntityTypeAddedConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_EntityTypeAddedConventions()'..

System Info:
EF Core version: 7.0.0-rc.1.22426.7
EFCore.NamingConventions version: 6.0.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL: 7.0.0-rc.1
Target framework: (e.g. .NET 5.0) .NET 6.0
Operating system: Windows 10/11
IDE: (e.g. Visual Studio 2019 16.3) Visual Studio 2022 17.3.5

**Comment by roji** [comment] 2022-09-29 23:03
Duplicate of #158

**Closed by roji** 2022-09-29 23:03 UTC
