### ISSUE TITLE
AspNet- tables remain unchanged when Snake Case convention is applied

### ISSUE THREAD

**Issue by aliakseiherman** [efcore/EFCore.NamingConventions#132] opened 2022-04-03 00:13 UTC
![image](https://user-images.githubusercontent.com/6156643/161405757-6214601e-7b88-4f08-be28-c7b918f3cd0a.png)

**Comment by roji** [comment] 2022-04-03 05:24
Duplicate of #2

**Closed by roji** 2022-04-03 05:24 UTC

**Comment by douglasg14b** [comment] 2023-12-06 05:00
Is there any final fix for this? #2 is closed but still appears to be an outstanding problem 🤔 

If Asp.Net is the problem, is that tracked there somewhere?

**Comment by lordfeck** [comment] 2023-12-11 18:40
@douglasg14b I had the same problem, personally I just adapted some code I found elsewhere as an extension:

```
public static class ModelBuilderExtensions
{
    public static void NameModelEntitiesInSnakeCase(this ModelBuilder modelBuilder)
    {
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        {
            // Replace table names
            entity.SetTableName(entity.GetTableName().ToSnakeCase());

            // Replace column names            
            foreach (var property in entity.GetProperties())
            {
                property.SetColumnName(property.GetColumnName().ToSnakeCase());
            }

            foreach (var key in entity.GetKeys())
            {
                key.SetName(key.GetName().ToSnakeCase());
            }

            foreach (var key in entity.GetForeignKeys())
            {
                key.SetConstraintName(key.GetConstraintName().ToSnakeCase());
            }

            foreach (var index in entity.GetIndexes())
            {
                index.SetDatabaseName(index.GetDatabaseName().ToSnakeCase());
            }
        }
    }
    public static string ToSnakeCase(this string input)
    {
        if (string.IsNullOrEmpty(input)) { return input; }

        var startUnderscores = Regex.Match(input, @"^_+");
        return startUnderscores + Regex.Replace(input, @"([a-z0-9])([A-Z])", "$1_$2").ToLower();
    }

}
```

Import that to your application DB context and in `onModelCreating` call NameModelEntitiesInSnakeCase() on your modelBuilder.

This will ensure all tables are named in snake_case.

**Comment by roji** [comment] 2024-01-03 18:36
@douglasg14b unfortunately the design of ASP.NET Identity's EF support and this naming conventions plugin are fundamentally incompatible; as I wrote in the other issue, since ASP.NET Identity explicitly sets names (just as if you, as a user, configured your column names explicitly), the plugin cannot override them since it functions as a "default" convention. 

In theory, it *may* be possible to look at changing the ASP.NET Identity side to not use explicit configuration, but rather be a convention itself, but I highly doubt time would be spent doing that. If you wish to pursue that, you can open an issue on the ASP.NET repo for Identity.
