### ISSUE TITLE
Name of the tables when there are discriminators

### ISSUE THREAD

**Issue by dianamazo** [efcore/EFCore.NamingConventions#194] opened 2023-05-04 19:24 UTC
Hello, thank you for your package, I have a concern.
when we have a table that works with discriminators and we configure it through fluent api, as in the following example:

```c#
public class CollaboratorConfiguration : IEntityTypeConfiguration<Collaborator>
{
    public void Configure(EntityTypeBuilder<Collaborator> builder)
    {
        **builder.HasDiscriminator**(hd => hd.CollaboratorType)
            .HasValue<Assistant>(CollaboratorType.Assistant)
            .HasValue<Auxiliary>(CollaboratorType.Auxiliary)
            .HasValue<Professional>(CollaboratorType.Professional)
            .HasValue<Typer>(CollaboratorType.Typer)
            .HasValue<Responsible>(CollaboratorType.Responsible);

        builder.HasOne<Speciality>()
            .WithMany()
            .HasForeignKey(fk => fk.SpecialityId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasIndex(i => i.Identification)
            .IsUnique();
    }
}
```

At the time of creating the migration it is not able to convert the table name to snake case.

Thanks for your support.

**Comment by at-besa** [comment] 2023-05-19 07:09
i guess this is the same as #184

**Comment by roji** [comment] 2024-01-03 13:36
Duplicate of #184

**Closed by roji** 2024-01-03 13:36 UTC
