### ISSUE TITLE
AspNet Core Identity tables names are not modified

### ISSUE THREAD

**Issue by jgilm** [efcore/EFCore.NamingConventions#284] opened 2024-07-06 18:54 UTC
Trying to use the lowercase naming convention and AspNet Core Identity, however the `AspNet...` tables are not affected by the convention. I noticed this when trying to create my own convention, but decided to use this package when I couldn't get my own to work correctly.

### Environment:
- .NET 8
- EF Core 8
- NpgSql

### Usage in DbContext
```csharp
    override protected void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        optionsBuilder.UseLowerCaseNamingConvention();
    }
```

Looking at the below example, see that the `AspNetRoles` and `AspNetUsers` tables are PascalCase, but my `Address` entity is converted to lowercase. So it looks like this is partially working, but for some reason not with the `AspNet...` entities. Although, notice that the column names and primary key names are lowercase even for the `AspNet...` entities

### Example migration.
```csharp
            migrationBuilder.CreateTable(
                name: "address",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<int>(type: "integer", nullable: false),
                    line1 = table.Column<string>(type: "text", nullable: false),
                    line2 = table.Column<string>(type: "text", nullable: false),
                    city = table.Column<string>(type: "text", nullable: false),
                    state = table.Column<string>(type: "text", nullable: false),
                    postcode = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_address", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetRoles",           // <========
                schema: "useraccounts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    normalizedname = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    concurrencystamp = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_aspnetroles", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                schema: "useraccounts",
                columns: table => new
...
```

### Workaround

As a workaround I am adding this convention and iterating over all entities and properties and lowercasing them here. It's working for me in my current project, but not sure if there will be some other issue later.

```csharp
public class LowercaseNamingConvention : IModelFinalizingConvention
{
    public void ProcessModelFinalizing(IConventionModelBuilder modelBuilder, IConventionContext<IConventionModelBuilder> context)
    {
        modelBuilder.Metadata.GetEntityTypes().ToList().ForEach(entityType =>
        {
            entityType.SetTableName(entityType.GetTableName().ToLower());

            entityType.GetProperties().ToList().ForEach(property =>
            {
                property.SetColumnName(property.GetColumnName().ToLower());
            });
        });
    }
}
```

**Comment by shearos** [comment] 2024-07-12 09:21
have you checked out this [issue](https://github.com/efcore/EFCore.NamingConventions/issues/2#issuecomment-612651161)

**Comment by roji** [comment] 2024-07-12 09:53
Duplicate of #2

**Closed by roji** 2024-07-12 09:53 UTC
