### ISSUE TITLE
Foreign key name changed after upgrade to 5.0.2

### ISSUE THREAD

**Issue by yunfandev** [efcore/EFCore.NamingConventions#64] opened 2021-01-25 08:49 UTC
After upgrade from [5.0.0](https://www.nuget.org/packages/EFCore.NamingConventions/5.0.1) to [5.0.2](https://www.nuget.org/packages/EFCore.NamingConventions/5.0.2), I found the foreign key name changed

![image](https://user-images.githubusercontent.com/8027453/105682315-44f4e800-5f2d-11eb-9fe5-68c8fdc01675.png)

**Comment by yunfandev** [comment] 2021-01-25 08:52
It seems that version 5.0.1 also has this problem

**Comment by roji** [comment] 2021-01-25 13:30
@yunfandev can you please submit a small code sample which shows this happening? I'm seeing foreign being rewritten fine, without dropping the `id` suffix.

**Comment by yunfandev** [comment] 2021-01-27 10:28
@roji I create a demo repo [ef-namingconventions-demo](https://github.com/yunfandev/ef-namingconventions-demo), you can clone this repo and try to upgrade package [EFCore.NamingConventions](https://www.nuget.org/packages/EFCore.NamingConventions/) to 5.0.2 or 5.0.1, then rebuild solution and try to add a new migration, you will get this 😂😂😂

```sh
.\migrate.ps1 -name UpgradePackage
```

![image](https://user-images.githubusercontent.com/8027453/105978370-6b518980-60cd-11eb-8da7-386eb61be176.png)

**Comment by yunfandev** [comment] 2021-01-29 05:58
@roji Can you reproduce the problem? 😅😅😅

**Comment by roji** [comment] 2021-01-29 12:12
@yunfandev thanks for the repro, and yes - I could reproduce it. However, this is actually by-design, i.e. a bug fix rather than a bug...

PostgreSQL has a built-in identifier limit of 63 characters. That means that if you try to create a table, column or foreign key with a name longer than 63 characters, it gets silently truncated. The EF Core provider automatically truncates names down to 63, and also "uniquifies" them - if multiple identifiers have the same name, a ~1, ~2 suffix is added to make sure they're unique.

Now, EFCore.NamingConventions 5.0.0 was written in a way which mistakenly did not go through this logic - this means that multiple long names would have been truncated by PG to the same identifier, causing severe bugs. 5.0.1 was fixed, so now you're seeing the truncation at work on EF Core's side.

There's nothing specifically wrong with the new, truncated name (even if it looks ugly). You can also configure an explicit, shorter name, that won't reach the limit and wouldn't require truncation. Note that snake_case introduces additional underscore characters, and so makes identifiers longer.

**Comment by roji** [comment] 2021-01-29 12:12
Am closing this for now as by design, but feel free to post back with any comments.

**Closed by roji** 2021-01-29 12:12 UTC
