### ISSUE TITLE
Primary key constraint names all become equal for types within a TPT (.NET 5-rc.2)

### ISSUE THREAD

**Issue by sandord** [efcore/EFCore.NamingConventions#39] opened 2020-09-24 15:20 UTC
When applying the snake case naming convention, primary key constraint names are generated incorrectly for tables that map to entities that are part of a TPT mapped hierarchy.

I'm on .NET 5.0.0-rc.2.20472.13 by the way.

Without applying the convention, the constraint names are generated correctly, corresponding to their table names.

The problem is that all derived classes get the same primary key constraint name, as can be seen in the generated migration:

    migrationBuilder.CreateTable(
        name: "players",
        columns: table => new
        {
            id = table.Column<int>(type: "INTEGER", nullable: false)
                .Annotation("Sqlite:Autoincrement", true),
            age = table.Column<int>(type: "INTEGER", nullable: false),
            name = table.Column<string>(type: "TEXT", nullable: true),
            team_id = table.Column<int>(type: "INTEGER", nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("pk_players", x => x.id); // <----------- pk_players (correct)
            table.ForeignKey(
                name: "fk_players_teams_team_id",
                column: x => x.team_id,
                principalTable: "teams",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        });

    migrationBuilder.CreateTable(
        name: "hitters",
        columns: table => new
        {
            id = table.Column<int>(type: "INTEGER", nullable: false)
                .Annotation("Sqlite:Autoincrement", true),
            home_runs = table.Column<int>(type: "INTEGER", nullable: false)
        },
        constraints: table =>
        {
            table.PrimaryKey("pk_players", x => x.id); // <----------- pk_players (incorrect, should have been pk_hitters)
            table.ForeignKey(
                name: "fk_hitters_players_id",
                column: x => x.id,
                principalTable: "players",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        });

    migrationBuilder.CreateTable(
        name: "pitchers",
        columns: table => new
        {
            id = table.Column<int>(type: "INTEGER", nullable: false)
                .Annotation("Sqlite:Autoincrement", true),
            strikeouts = table.Column<int>(type: "INTEGER", nullable: false)
        },
        constraints: table =>
        {
            table.PrimaryKey("pk_players", x => x.id); // <----------- pk_players (incorrect, should have been pk_pitchers)
            table.ForeignKey(
                name: "fk_pitchers_players_id",
                column: x => x.id,
                principalTable: "players",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        });

Obviously, this is incorrect and when applying the convention a SQL error occurs because primary key constraint names are required to be unique.

The following project demonstrates the problem:

[Example.zip](https://github.com/efcore/EFCore.NamingConventions/files/5277176/Example.zip)

Also, I'm seeing errors like this: 

    The foreign keys {'BankId'} on 'Debtor' and {'BankId'} on 'Creditor' are both mapped to
    'Roles.fk_roles_roles_bank_id' but use different columns ({'Debtor_bank_id'} and {'bank_id'}).

Clearly, the `Debtor_bank_id` is not affected by the naming convention (while it should). This concerns a TPH scenario by the way.

**Comment by sandord** [comment] 2020-09-25 11:41
This appears to be a problem with EFCore, not EFCore.NamingConventions specifically: https://github.com/dotnet/efcore/issues/22753

**Comment by roji** [comment] 2020-11-26 16:58
Sorry for not looking at this earlier - I agree this looks like a result of https://github.com/dotnet/efcore/issues/19811 (which replaced dotnet/efcore#22753). Am closing this until that issue is fixed - let's revisit after that.

**Comment by roji** [comment] 2020-11-26 16:58
Duplicate of dotnet/efcore#19811

**Closed by roji** 2020-11-26 16:58 UTC
