### ISSUE TITLE
EF Core 6 - Invalid model snapshot for views when using default schema

### ISSUE THREAD

**Issue by llRandom** [efcore/EFCore.NamingConventions#115] opened 2021-11-26 16:24 UTC
I have the following DbContext definition:

```C#
public class MyDbContext : DbContext
{
    public DbSet<UserView> UserViews { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("fake");
        optionsBuilder.UseSnakeCaseNamingConvention();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("test");
        modelBuilder.Entity<UserView>().ToView("users_view", "security");
    }
}

public class UserView
{
    public long Id { get; set; }
}
```

If I create an initial migration I get the following snapshot definition:

```C#
modelBuilder.Entity("WebApplication1.UserView", b =>
    {
        b.Property<long>("Id")
            .HasColumnType("bigint")
            .HasColumnName("id");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

        b.HasKey("Id")
            .HasName("pk_user_views");

        b.ToTable(null, "test"); // this line throws an exception when trying to create the next migration

        b.ToView("users_view", "security");
    });
```

When I'm trying to add a new migration it fails on this line from the snapshot: `b.ToTable(null, "test");` because `null` table name is not valid:
```
PM> add-migration tmp
Build started...
Build succeeded.
```

> System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToTable(EntityTypeBuilder entityTypeBuilder, String name, String schema)
   at WebApplication1.Migrations.MyDbContextModelSnapshot.<>c.<BuildModel>b__0_1(EntityTypeBuilder b) in C:\Projects\WebApplication1\WebApplication1\Migrations\MyDbContextModelSnapshot.cs:line 61
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action\`1 buildAction)
   at WebApplication1.Migrations.MyDbContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in C:\Projects\WebApplication1\WebApplication1\Migrations\MyDbContextModelSnapshot.cs:line 50
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.CreateModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.get_Model()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'name')

Without `UseSnakeCaseNamingConvention` call snapshot doesn't have this `ToTable` call, only `ToView`. If default schema is not set it still has `ToTable` call but it doesn't throw an exception. It was working fine on EF Core 5

**Comment by ajcvickers** [comment] 2021-11-28 13:13
This is a duplicate of https://github.com/dotnet/efcore/issues/26651, which is fixed ready for the 6.0.1 patch release.

**Closed** 2024-01-03 16:56 UTC
